cursor_trail 100

scrollback_lines 10000

# BEGIN_KITTY_FONTS
font_family      family='DejaVu Sans Mono' postscript_name=DejaVuSansMono
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Strange: with font size 9, there are artifacts (torn/truncated letters, especially 'm' in italics). With font size
# 9.5, displayed font height is the same, they are slightly wider, mostly without artifacts... except for capital 'M',
# italics.
# Quote from https://sw.kovidgoyal.net/kitty/faq/:
# > Similarly, some monospaced font families are buggy and have bold or italic faces that have characters wider than the
# > width of the normal face, these will also result in clipping. Such issues should be reported to the font developer.
# > Monospaced font families must have all their characters rendered within a fixed width across all faces of the font,
# > otherwise they aren’t really monospaced.
# However, GNOME Terminal does not have any issue with them.
font_size 9.5

kitty_mod ctrl+shift

map alt+right next_tab
map alt+left previous_tab

map kitty_mod+equal change_font_size current +2.0
map kitty_mod+plus change_font_size current +2.0
map kitty_mod+kp_add change_font_size current +2.0

map kitty_mod+minus change_font_size current -2.0
map kitty_mod+kp_subtract change_font_size current -2.0
